config/routes.rb
Rails.application.routes.draw do
  resources :events
  devise_for :admins
  devise_for :accounts, controllers: { registrations: "registrations" }

  root 'pages#index'

  match '/contacts', to: 'pages#index', via: 'get'
  resources "contacts", only: [:new, :create]
  
  resources :students do
    collection do
      get 'search'
      get 'admin_search'
      post 'reset'
      post 'transfer'
    end
  end

  resources :groupslots do
    collection do
      post 'reset'
      post 'clean_groups'
    end
  end

  resources :admins do
    collection do
      get 'index'
      get 'accounts'
      get 'students'
      get 'timeslots'
      get 'writeups'
      post 'clean_timeslots'
    end
  end

  match 'accounts/:id' => 'accounts#destroy', :via => :delete, :as => :destroy_account

  resources :accounts do
    collection do
      get 'index'
      get 'search'
      get 'sign_ups'
      get 'group_signups'
      post 'group_signup'
      get 'slot'
      get 'slip'
      get 'groupslip'
      post 'admin_writeup'
      post 'reset_writeup'
      post 'reset_feedback'
      post 'sign_up'
      post 'photoshoot'
      post 'reschedule'
      get 'timeslots'
      get 'add_writeup'
      get 'edit_info'
      get 'submit_writeup'
      post 'submit_final_writeup'
      get 'yearbook_preview'
      post 'addfeedback'
    end
  end

 

  get "*any", via: :all, to: "pages#not_found"
end

app/views/admins/accounts.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class=""><%= link_to 'DASHBOARD', admins_path, method: :get %></li>
        <li class=""><%= link_to 'STUDENTS', students_admins_path, method: :get %></li>
        <li><%= link_to 'EVENTS', events_path, method: :get %></li>
        <li class="active"><%= link_to 'ACCOUNTS', accounts_admins_path, method: :get %></li>
        <li><%= link_to 'TIMESLOTS', timeslots_admins_path, method: :get %></li>
        <li><%= link_to 'WRITEUPS', writeups_admins_path, method: :get %></li>
        <li><%= link_to "LOG OUT", destroy_admin_session_path, :method => :delete %></a>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class="container with-fixed-navbar admins">
  <div class="row">
    <div class="col-xs-12">
    <h3 class="center-align">Search</h3>
      <div class="col-xs-12 col-sm-4 col-sm-offset-4 search-form">
        <input type="number" name="id" id="search_account">
        <label for="search">ID Number</label>
      </div>
      <div class="col-xs-4 col-xs-offset-4">
        <table class="search-table table">
          <tr>
            <th>Name</th>
            <td id="student-name"></td>
          </tr>
          <tr>
            <th>Year & Course</th>
            <td id="student-yrcrs"></td>
          </tr>
          <tr>
            <th>School</th>
            <td id="student-school"></td>
          </tr>
          <tr>
            <th>Email</th>
            <td id="student-email"></td>
          </tr>
          <tr>
            <th>Timeslot</th>
            <td id="student-timeslot"></td>
          </tr>
          <tr>
            <th>Feedback</th>
            <td id="student-writeup" style="white-space: pre-line;"></td>
          </tr>
        </table>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12">
      <h3 class="center-align">Accounts</h3>
      <h4 class="center-align">Number of accounts: <span class="text-bold"><%=@account_number %></span>/<%= Student.count %></h4>
      <h4 class="center-align"><%= flash[:notice] %></h4>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12">
      <table class="table-striped table">
        <tr>
          <th class="right-align">Student ID</th>
          <th>Name</th>
          <th>Email</th>
          <th class="right-align">Year</th>
          <th>Course</th>
          <th>School</th>
          <th>Writeup</th>
          <th>Feedback</th>
          <th></th>
        </tr>
        <% @accounts.each do |student| %> 
          <tr>
            <td class="right-align"><%= student.student_id %></td>
            <td><%= student.name %></td>
            <td><%= student.email %></td>
            <td class="right-align"><%= student.yr %></td>
            <td><%= student.course %></td>
            <td><%= student.school %></td>
            <td style="white-space: pre-line;"><%= student.writeup %></td>
            <td><%= student.feedback %></td>
          </tr>
        <% end %>
      </table>
      
    </div>
  </div>
  <div class="row">
    <div class="flex col-xs-12"><%= will_paginate @accounts %></div>
  </div>
</div>

app/views/admins/index.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to 'DASHBOARD', admins_path, method: :get %></li>
        <li class=""><%= link_to 'STUDENTS', students_admins_path, method: :get %></li>
        <li><%= link_to 'EVENTS', events_path, method: :get %></li>
        <li><%= link_to 'ACCOUNTS', accounts_admins_path, method: :get %></li>
        <li><%= link_to 'TIMESLOTS', timeslots_admins_path, method: :get %></li>
        <li><%= link_to 'WRITEUPS', writeups_admins_path, method: :get %></li>
        <li><%= link_to "LOG OUT", destroy_admin_session_path, :method => :delete %></a>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class="container with-fixed-navbar">
 <h4 class="center-align"><%= flash[:notice] %></h4>
  <div class="row">
    <div class="col-xs-12 col-md-8">
      <h3 class="center-align">Accounts Summary</h3>
      <table class="table-striped table">
        <tr>
          <th >School</th>
          <th class="right-align">Number of students</th>
          <th class="right-align">Number of accounts</th>
          <th class="right-align">Accounts %</th>
          <th class="right-align">Feedback</th>
          
        </tr>
        <tr>
          <td>SOH</td>
          <td class="right-align"><%=@soh_students%></td>
          <td class="right-align"><%=@soh_accounts%></td>
          <td class="right-align"><%=(@soh_accounts/@soh_students.to_f).round(2)%></td>
          <td class="right-align"><%=@soh_feedback%></td>
        </tr>
        <tr>
          <td>SOM</td>
          <td class="right-align"><%=@som_students%></td>
          <td class="right-align"><%=@som_accounts%></td>
          <td class="right-align"><%=(@som_accounts/@som_students.to_f).round(2)%></td>
          <td class="right-align"><%=@som_feedback%></td>
        </tr>
        <tr>
          <td>SOSE</td>
          <td class="right-align"><%=@sose_students%></td>
          <td class="right-align"><%=@sose_accounts%></td>
          <td class="right-align"><%=(@sose_accounts/@sose_students.to_f).round(2)%></td>
          <td class="right-align"><%=@sose_feedback%></td>
        </tr>
        <tr>
          <td>SOSS</td>
          <td class="right-align"><%=@soss_students%></td>
          <td class="right-align"><%=@soss_accounts%></td>
          <td class="right-align"><%=(@soss_accounts/@soss_students.to_f).round(2)%></td>
          <td class="right-align"><%=@soss_feedback%></td>
        </tr>
        <tr>
          <td class="text-bold">Sum</td>
          <td class="right-align text-bold"><%=@students%></td>
          <td class="right-align text-bold"><%=@accounts%></td>
          <td class="right-align text-bold"><%=(@accounts/@students.to_f).round(2)%></td>
          <td class="right-align text-bold"><%=@total_feedback%></td>

          
        </tr>
      </table>
      <p>
        <%= link_to "Download Writeup Compilation", admins_path(format: "csv") %><br>
      </p>
    </div>
    <div class="col-xs-12 col-md-4">
      <h3 class="center-align">Errors Summary</h3>
      <table class="table table-striped">
        <tr>
          <td>Empty accounts: <%=@error_accounts.count%></td>
          <td>
            <% @error_accounts.each do |account|%>
              <%= account.student_id %> <br/>
            <% end %>    
          </td>
        </tr>
        <tr>
          <td>Students records with accounts: <%= @true_accounts %></td>
          <td>  
          </td>
        </tr>
        <tr>
          <td>Student - Account: </td>
          <td class="left-align">
            <% @a.each do |student| %>
              <%= student.id %> <br/>
            <% end %>
          </td>
        </tr>
        <tr>
          <td>Account - Student: </td>
          <td class="left-align">
            <% @b.each do |account| %>
              <%= account.student_id %> <br/>
            <% end %>
          </td>
        </tr>
      </table>
      <h3 class="center-align">Change Student Record</h3>
      <form action="/students/reset" method="POST">
        <input type="number" name="id">
        <button type="submit">Change</button>
      </form>

      <h3 class="center-align">Transfer Student Details</h3>
      <form action="/students/transfer" method="POST">
        <input type="number" name="id">
        <button type="submit">Transfer</button>
      </form>

      <h3 class="center-align">Reset Finalized Write-up</h3>
      <form action="/accounts/reset_writeup" method="POST">
        <input type="number" name="id">
        <button type="submit">Transfer</button>
      </form>

      <h3 class="center-align">Reset Feedback</h3>
      <form action="/accounts/reset_feedback" method="POST">
        <input type="number" name="id">
        <button type="submit">Reset</button>
      </form>

    </div>
  </div>
  <div class="row">
    
  </div>
</div>

app/views/admins/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">ID</Data></Cell>
        <Cell><Data ss:Type="String">Name</Data></Cell>
        <Cell><Data ss:Type="String">Year</Data></Cell>
        <Cell><Data ss:Type="String">Course</Data></Cell>
      </Row>
    <% @accounts.each do |account| %>
      <Row>
        <Cell><Data ss:Type="String"><%= account.student_id %></Data></Cell>
        <Cell><Data ss:Type="String"><%= account.name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= account.yr %></Data></Cell>
        <Cell><Data ss:Type="String"><%= account.course %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/admins/new.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'HOME', root_path, method: :get %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">LOGIN <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li>
        <form class="navbar-form navbar-left">
              <div class="form-group">
                <input type="text" class="form-control" placeholder="Search">
              </div>
              <button type="submit" class="btn btn-default">Submit</button>
          </form>
        </li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class="container">
  <div class="row">
    <div class="col-xs-10 col-xs-offset-1 col-sm-offset-4">
      <h1>Register</h1>
      <h5>Create an account for photoshoot sign-ups, write-up submissions and online previews.</h5>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-10 col-xs-offset-1 col-sm-6 col-sm-offset-5">

      <%= simple_form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
        <%= devise_error_messages! %>

        <h4>Student information</h4>
        

        <h4>Account details</h4>
        <div class="field">
          <%= f.label :email, "Email" %>
          <%= f.email_field :email, label: false %>
        </div>

        <div class="field">
          <%= f.label :password %>
          <% if @minimum_password_length %>
          <em>(<%= @minimum_password_length %> characters minimum)</em>
          <% end %><br />
          <%= f.password_field :password, autocomplete: "off" %>
        </div>

        <div class="field">
          <%= f.label :password_confirmation %><br />
          <%= f.password_field :password_confirmation, autocomplete: "off" %>
        </div>

        <div class="actions">
          <%= f.submit "Sign up" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<%= render "devise/shared/links" %>

app/views/admins/students.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class=""><%= link_to 'DASHBOARD', admins_path, method: :get %></li>
        <li class="active"><%= link_to 'STUDENTS', students_admins_path, method: :get %></li>
        <li><%= link_to 'EVENTS', events_path, method: :get %></li>
        <li><%= link_to 'ACCOUNTS', accounts_admins_path, method: :get %></li>
        <li><%= link_to 'TIMESLOTS', timeslots_admins_path, method: :get %></li>
        <li><%= link_to 'WRITEUPS', writeups_admins_path, method: :get %></li>
        <li><%= link_to "LOG OUT", destroy_admin_session_path, :method => :delete %></a>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class="container with-fixed-navbar">
  <div class="row">
    <div class="col-xs-12">
    <h3 class="center-align">Search</h3>
      <div class="col-xs-12 col-sm-4 col-sm-offset-4 search-form">
        <input type="number" name="id" id="search_student">
        <label for="search">ID Number</label>
      </div>
      <div class="col-xs-4 col-xs-offset-4">
        <table class="search-table table">
          <tr>
            <th>Name</th>
            <td id="student-name"></td>
          </tr>
          <tr>
            <th>Year & Course</th>
            <td id="student-yrcrs"></td>
          </tr>
          <tr>
            <th>School</th>
            <td id="student-school"></td>
          </tr>
          <tr>
            <th>With account?</th>
            <td id="student-account"></td>
          </tr>
          <tr>
            <th>Yearbook page number</th>
            <td id="student-yrbookpage"></td>
          </tr>
        </table>
      </div>
    </div>
    <div class="col-xs-12">
      <h3 class="center-align">Students</h3>
      <table class="table-striped table">
        <tr>
          <th class="right-align">Student ID</th>
          <th>Name</th>
          <th class="right-align">Year</th>
          <th>Course</th>
          <th>School</th>
          <th class="right-align">Page number</th>
        </tr>
        <% @students.each do |student| %> 
          <tr class=<%=student.account ? "success":"warning" %>>
            <td class="right-align"><%= student.id %></td>
            <td><%= student.name.html_safe %></td>
            <td class="right-align"><%= student.yr %></td>
            <td><%= student.course %></td>
            <td><%= student.school %></td>
            <td class="right-align"><%= student.page_number %></td>
          </tr>
        <% end %>
      </table>
      
    </div>
  </div>
  <div class="row">
    <div class="flex col-xs-12"><%= will_paginate @students %></div>
  </div>
</div>

app/views/admins/timeslots.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'DASHBOARD', admins_path, method: :get %></li>
        <li class=""><%= link_to 'STUDENTS', students_admins_path, method: :get %></li>
        <li><%= link_to 'EVENTS', events_path, method: :get %></li>
        <li><%= link_to 'ACCOUNTS', accounts_admins_path, method: :get %></li>
        <li class="active"><%= link_to 'TIMESLOTS', timeslots_admins_path, method: :get %></li>
        <li><%= link_to 'WRITEUPS', writeups_admins_path, method: :get %></li>
        <li><%= link_to "LOG OUT", destroy_admin_session_path, :method => :delete %></a>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class="container with-fixed-navbar">
  <div class="tab-content">
    <div class="table-responsive" id="summary" role="tabpanel" class="tab-pane active fade in">
      <table class="table table-striped">
        <h3 class="center-align">SUMMARY</h3>
        <tr>
          <th class="right-align">DATE</th>
          <th>School</th>
          <th class="right-align">8:00AM<br>9:00AM</th>
          <th class="right-align">9:00AM<br>10:00AM</th>
          <th class="right-align">10:00AM<br>11:00AM</th>
          <th class="right-align">11:00AM<br>12:00PM</th>
          <th class="right-align">12:00PM<br>1:00PM</th>
          <th class="right-align">1:00PM<br>2:00PM</th>
          <th class="right-align">2:00PM<br>3:00PM</th>
          <th class="right-align">3:00PM<br>4:00PM</th>
          <th class="right-align">4:00PM<br>5:00PM</th>
          <th class="right-align">5:00PM<br>6:00PM</th>
          <th class="right-align">Slots left:<br><%=Timeslot.sum(:slots)%></th>
        </tr>
        <% @dates.each do |date| %>
          <tr>
            <td class="right-align text-bold"><%= Date.parse(date.dasherize).strftime("%a, %b %d") %></td>
            <td>
            <% if ["2016-10-17", "2016-10-18", "2016-10-19"].include? date.dasherize %>
              <%= "SOH" %>
            <% elsif ["2016-10-20","2016-10-21","2016-10-22","2016-10-24","2016-10-25","2016-10-26"].include? date.dasherize %>
              <%= "SOSS " %>
            <% end %>
            <% if ["2016-10-26", "2016-10-27","2016-10-28","2016-10-29","2016-11-03","2016-11-04"].include? date.dasherize %>
              <%= "SOSE " %>
            <% end %>
            <% if ["2016-11-04","2016-11-07","2016-11-08","2016-11-09","2016-11-10","2016-11-14","2016-11-15"].include? date.dasherize %>
              <%= "SOM" %>
            <% end %></td>
            <% @sum = 0%>
            <% instance_variable_get("@slots_#{date}").order(:start_time).each do |slot| %>
              <% @sum = @sum + slot.slots %>
              <% if slot.slots >= 6 %>
                <% @status = "success" %>
              <% elsif slot.slots < 6 && slot.slots > 0 %>
                <% @status = "warning" %>
              <% elsif slot.slots == 0 %>
                <% @status = "danger" %>
              <% end %>
              <td class="right-align <%= @status %>"><%= slot.slots %></td>
            <% end %>
            <td class="right-align text-bold"><%= @sum %></td>
          </tr>
        <% end %>
        <% @dates_g.each do |date| %>
          <tr>
            <td class="right-align text-bold"><%= Date.parse(date.dasherize).strftime("%a, %b %d") %></td>
            <td>
            Group</td>
            <% @sum = 0%>
            <% instance_variable_get("@slots_#{date}").order(:start_time).each do |slot| %>
              <% @sum = @sum + slot.slots %>
              <% if slot.slots >= 6 %>
                <% @status = "success" %>
              <% elsif slot.slots < 6 && slot.slots > 0 %>
                <% @status = "warning" %>
              <% elsif slot.slots == 0 %>
                <% @status = "danger" %>
              <% end %>
              <td class="right-align <%= @status %>"><%= slot.slots %></td>
            <% end %>
            <td class="right-align text-bold"><%= @sum %></td>
          </tr>
        <% end %>
      </table>
    </div>

    <div class="table-responsive" id="detailed" role="tabpanel" class="tab-pane fade">
      <h3 class="center-align">DETAILED</h3>
      <%= link_to "Excel", timeslots_admins_path(format: "xls") %>
      <% @dates.each do |date| %>
        <div class="col-xs-12 col-sm-8 col-sm-offset-2">
          <table class="table">
            <h5 class="center-align text-bold"><%= Date.parse(date.dasherize).strftime("%a, %b %d")%></h5>
            <tr>
              <th>Time</th>
              <th class="right-align">Slots</th>
              <th>Students</th>  
            </tr>
            <% instance_variable_get("@slots_#{date}").order(:start_time).each do |slot| %>
              <tr>
                <td><%= slot.start_time + " - " + slot.end_time %></td>
                <td class="right-align"><%= slot.slots%> </td>
                <td>
                  <% Account.where(timeslot_id: slot.id).order(:student_id).each do |account | %>
                    <%= account.to_s %><br>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </table>
        </div>
      <% end %>

      <% @dates_g.each do |date| %>
        <div class="col-xs-12 col-sm-8 col-sm-offset-2">
          <table class="table">
            <h5 class="center-align text-bold"><%= Date.parse(date.dasherize).strftime("%a, %b %d")%></h5>
            <tr>
              <th>Time</th>
              <th class="right-align">Slots</th>
              <th>Groups</th>  
            </tr>
            <% instance_variable_get("@slots_#{date}").order(:start_time).each do |slot| %>
              <tr>
                <td><%= slot.start_time + " - " + slot.end_time %></td>
                <td class="right-align"><%= slot.slots%> </td>
                <td>
                  <% Groupslot.where(groupshot_id: slot.id).order(:group_name).each do |group | %>
                    <%= group.group_name + " c/o " + Account.where(student_id: group.student_id).first.to_s %><br>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </table>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admins/timeslots.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
    <Worksheet ss:Name="Sheet1">
      <% @dates.each do |date| %>
      <Table>
        <Row>
          <Cell><Data ss:Type="String"><%= Date.parse(date.dasherize).strftime("%a, %b %d")%></Data></Cell>
        </Row>
        <Row>
          <Cell><Data ss:Type="String">Time</Data></Cell>
          <Cell><Data ss:Type="String">Slots</Data></Cell>
          <Cell><Data ss:Type="String">Students</Data></Cell>
        </Row>
      <% instance_variable_get("@slots_#{date}").order(:start_time).each do |slot| %>
        <Row>
          <Cell><Data ss:MergeDown="15" ss:Type="String"><%= slot.start_time + " - " + slot.end_time %></Data></Cell>
          <Cell><Data ss:MergeDown="15" ss:Type="Number"><%= slot.slots %></Data></Cell>
            <% Account.where(timeslot_id: slot.id).order(:student_id).each do |account | %> 
                <Row><Cell><Data ss:Type="String">          
                    <%= account.to_s %><br>
                </Data></Cell></Row>
            <% end %>
        </Row>
      <% end %>
      </Table>
    <% end %>
    </Worksheet>
</Workbook>

app/views/admins/writeups.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class=""><%= link_to 'DASHBOARD', admins_path, method: :get %></li>
        <li class=""><%= link_to 'STUDENTS', students_admins_path, method: :get %></li>
        <li><%= link_to 'EVENTS', events_path, method: :get %></li>
        <li><%= link_to 'ACCOUNTS', accounts_admins_path, method: :get %></li>
        <li><%= link_to 'TIMESLOTS', timeslots_admins_path, method: :get %></li>
        <li class="active"><%= link_to 'WRITEUPS', writeups_admins_path, method: :get %></li>
        <li><%= link_to "LOG OUT", destroy_admin_session_path, :method => :delete %></a>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class="container with-fixed-navbar writeup">
  <div class="row">
    <div class="col-xs-offset-1 col-xs-9">
      <h1>Add Student Write-up</h3>
      <br>
      <h4 class="center-align"><%= flash[:notice] %></h4>
      <form action="/accounts/admin_writeup" method="POST">
        <div class="col-xs-12">
          <div class="col-xs-offset-2 col-xs-2">
            <label for="id">ID Number</label>
          </div>
          <div class="col-xs-7">
            <input type="number" name="id">
          </div>
        </div>
        &nbsp;
        <div class="col-xs-12">
          <div class="col-xs-offset-2 col-xs-2">
            <label for="writeup">Writeup</label>
          </div>
          <div class="col-xs-7">
            <textarea name="writeup" cols="70" rows="5" maxLength="500"></textarea>
          </div>
        </div>
        <div class="col-xs-offset-5">
          <br><br><br><br>
          <button type="submit">Add Writeup</button>
        </div>
      </form>
    </div>
  </div>
  
</div>