config/routes.rb
Rails.application.routes.draw do
  resources :events
  devise_for :admins
  devise_for :accounts, controllers: { registrations: "registrations" }

  root 'pages#index'

  match '/contacts', to: 'pages#index', via: 'get'
  resources "contacts", only: [:new, :create]
  
  resources :students do
    collection do
      get 'search'
      get 'admin_search'
      post 'reset'
      post 'transfer'
    end
  end

  resources :groupslots do
    collection do
      post 'reset'
      post 'clean_groups'
    end
  end

  resources :admins do
    collection do
      get 'index'
      get 'accounts'
      get 'students'
      get 'timeslots'
      get 'writeups'
      post 'clean_timeslots'
    end
  end

  match 'accounts/:id' => 'accounts#destroy', :via => :delete, :as => :destroy_account

  resources :accounts do
    collection do
      get 'index'
      get 'search'
      get 'sign_ups'
      get 'group_signups'
      post 'group_signup'
      get 'slot'
      get 'slip'
      get 'groupslip'
      post 'admin_writeup'
      post 'reset_writeup'
      post 'reset_feedback'
      post 'sign_up'
      post 'photoshoot'
      post 'reschedule'
      get 'timeslots'
      get 'add_writeup'
      get 'edit_info'
      get 'submit_writeup'
      post 'submit_final_writeup'
      get 'yearbook_preview'
      post 'addfeedback'
    end
  end

 

  get "*any", via: :all, to: "pages#not_found"
end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_admin!, :except => [:index]
  

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show

  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :description, :start_time, :end_time)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <br>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :start_time %><br>
    <%= f.date_select :start_time %>
  </div>
  <div class="field">
    <%= f.label :end_time %><br>
    <p>(+1 of end date)</p>
    <%= f.date_select :end_time %>
  </div>
  <br>
  <br>
  <div class="actions">
    <%= f.submit :class => "event-submit"%>
  </div>
<% end %>

app/views/events/edit.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
     </div>
     <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'STUDENTS', admins_path, method: :get %></li>
        <li class="active"><%= link_to 'EVENTS', events_path, method: :get %></li>
        <li><%= link_to 'ACCOUNTS', accounts_admins_path, method: :get %></li>
        <li><%= link_to "LOG OUT", destroy_admin_session_path, :method => :delete %></a>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<br><br><br><br>

<div class="row">
    <div class="col-xs-10 col-xs-offset-1 col-sm-6 col-sm-offset-3">
    <h1>Edit Event</h1>
    <br>
	    <div class="col-xs-10 col-xs-offset-1 col-sm-6 col-sm-offset-2">
		<%= render 'form' %>
		<%= link_to 'Back', events_path, :class => "event-back" %>
		</div>
	</div>
</div>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
     </div>
     <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class=""><%= link_to 'DASHBOARD', admins_path, method: :get %></li>
        <li><%= link_to 'STUDENTS', admins_path, method: :get %></li>
        <li class="active"><%= link_to 'EVENTS', events_path, method: :get %></li>
        <li><%= link_to 'ACCOUNTS', accounts_admins_path, method: :get %></li>
        <li><%= link_to 'TIMESLOTS', timeslots_admins_path, method: :get %></li>
        <li><%= link_to 'WRITEUPS', writeups_admins_path, method: :get %></li>
        <li><%= link_to "LOG OUT", destroy_admin_session_path, :method => :delete %></a>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class="container with-fixed-navbar admins">
  <div class="row">
    <div class="col-xs-12">
      <% if admin_signed_in? %><%= link_to 'New Event', new_event_path, :class => "event-new" %><% end %>
      <br>
      <br>
      <table class="table-striped table">
        <tr>
          <th>Title</th>
          <th>Description</th>
          <th>Start Date</th>
          <th>End Date</th>
          <th colspan="2"></th>
        </tr>
        <% @events.each do |event| %>
          <tr class="event-table">
            <td><%= event.title %></td>
            <td><%= event.description %></td>
            <td><%= event.start_time %></td>
            <td><%= event.end_time %></td>
            <% if admin_signed_in? %><td class="right-align"><%= link_to 'Edit', edit_event_path(event), :class => "event-crud" %></td>
            <td class="right-align"><%= link_to 'Delete', event, method: :delete, data: { confirm: 'Are you sure you want to delete this event?' }, :class => "event-crud" %></td><% end %>
          </tr>
        <% end %>
      </table>
      <br>
    </div>
  </div>
</div>
</div>

app/views/events/new.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
     </div>
     <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'STUDENTS', admins_path, method: :get %></li>
        <li class="active"><%= link_to 'EVENTS', events_path, method: :get %></li>
        <li><%= link_to 'ACCOUNTS', accounts_admins_path, method: :get %></li>
        <li><%= link_to "LOG OUT", destroy_admin_session_path, :method => :delete %></a>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<br><br><br><br>

<div class="row">
    <div class="col-xs-10 col-xs-offset-1 col-sm-6 col-sm-offset-3">
    <h1>Add Event</h1>
    <br>
	    <div class="col-xs-10 col-xs-offset-1 col-sm-6 col-sm-offset-2">
		<%= render 'form' %>
		<%= link_to 'Back', events_path, :class => "event-back" %>
		</div>
	</div>
</div>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'STUDENTS', admins_path, method: :get %></li>
        <li class="active"><%= link_to 'EVENTS', events_path, method: :get %></li>
        <li><%= link_to 'ACCOUNTS', accounts_admins_path, method: :get %></li>
        <li><%= link_to "LOG OUT", destroy_admin_session_path, :method => :delete %></a>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<br><br><br><br>

<div class="row">
    <div class="col-xs-10 col-xs-offset-1 col-sm-6 col-sm-offset-3">
    <h1><strong>Event:</strong> <br><%= @event.title %></h1>
    <br>
	    <p>
		  <strong>Description:</strong>
		  <%= @event.description %>
		</p>
		<p>
		  <strong>Start time:</strong>
		  <%= @event.start_time %>
		</p>
		<p>
		  <strong>End time:</strong>
		  <%= @event.end_time %>
		</p>
		<br>
		<%= link_to 'Edit', edit_event_path(@event), :class => "event-back" %> |
		<%= link_to 'Back', events_path, :class => "event-back" %>
		</div>
	</div>
</div>