config/routes.rb
Rails.application.routes.draw do
  resources :events
  devise_for :admins
  devise_for :accounts, controllers: { registrations: "registrations" }

  root 'pages#index'

  match '/contacts', to: 'pages#index', via: 'get'
  resources "contacts", only: [:new, :create]
  
  resources :students do
    collection do
      get 'search'
      get 'admin_search'
      post 'reset'
      post 'transfer'
    end
  end

  resources :groupslots do
    collection do
      post 'reset'
      post 'clean_groups'
    end
  end

  resources :admins do
    collection do
      get 'index'
      get 'accounts'
      get 'students'
      get 'timeslots'
      get 'writeups'
      post 'clean_timeslots'
    end
  end

  match 'accounts/:id' => 'accounts#destroy', :via => :delete, :as => :destroy_account

  resources :accounts do
    collection do
      get 'index'
      get 'search'
      get 'sign_ups'
      get 'group_signups'
      post 'group_signup'
      get 'slot'
      get 'slip'
      get 'groupslip'
      post 'admin_writeup'
      post 'reset_writeup'
      post 'reset_feedback'
      post 'sign_up'
      post 'photoshoot'
      post 'reschedule'
      get 'timeslots'
      get 'add_writeup'
      get 'edit_info'
      get 'submit_writeup'
      post 'submit_final_writeup'
      get 'yearbook_preview'
      post 'addfeedback'
    end
  end

 

  get "*any", via: :all, to: "pages#not_found"
end

app/models/account.rb
class Account < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :authentication_keys => [:student_id]
  belongs_to :timeslot
  belongs_to :groupshot
  # validates_uniqueness_of :email, :student_id
  validates :writeup, length: { maximum: 505 }
  validates :cellphone_number, :numericality => true, :allow_blank => true
  
  def to_s
    "#{self.student_id}, #{self.name}, #{self.yr} - #{self.course}"
  end

  def can_write
    if WriteupAccount.find_by(idnumber: self.student_id).nil?
      return false
    else
      return true
    end
  end

  def yearbook_shot
    @casualshot = Student.find(self.student_id).page_number
    case @casualshot.to_s.length
    when 2
      return "/pics/00"+@casualshot.to_s+".pdf"
    when 3
      return "/pics/0"+@casualshot.to_s+".pdf"
    when 4
      return "/pics/"+@casualshot.to_s+".pdf"
    end

  end

  def get_timeslot
    Timeslot.find_by(id: self.timeslot_id).to_s
  end

  def active_for_authentication?
    super and self.can_login
  end

  def inactive_message
    # @SOHstart = Time.new(2016, 10, 2,23).in_time_zone('Hong Kong')
    # @SOHend = Time.new(2016, 10, 3, 15).in_time_zone('Hong Kong')

    # @SOSSstart = Time.new(2016, 10, 3, 23).in_time_zone('Hong Kong')
    # @SOSSend = Time.new(2016, 10, 4, 15).in_time_zone('Hong Kong')

    # @SOSEstart = Time.new(2016, 10, 4, 23).in_time_zone('Hong Kong')
    # @SOSEend = Time.new(2016, 10, 5, 15).in_time_zone('Hong Kong')

    # @SOMstart = Time.new(2016, 10, 5, 23).in_time_zone('Hong Kong')
    # @SOMend = Time.new(2016, 10, 6, 15).in_time_zone('Hong Kong')

    # @groupstart1 = Time.new(2016, 10, 6, 23).in_time_zone('Hong Kong')
    # @groupend1 = Time.new(2016, 10, 7, 15).in_time_zone('Hong Kong')

    # @groupstart2 = Time.new(2016, 10, 7, 23).in_time_zone('Hong Kong')
    # @groupend2 = Time.new(2016, 10, 8, 15).in_time_zone('Hong Kong')

    # @somspecialstart = Time.new(2016, 10, 8, 23).in_time_zone('Hong Kong')
    # @somspecialend = Time.new(2016, 10, 9, 15).in_time_zone('Hong Kong')

    # case self.school
    # when "SOH" 
    #     return "You may only login between " + @SOHstart.strftime("%b %d, %I:%M") + " AM and " + @SOHend.strftime("%b %d, %I:%M")  +" PM. "
    # when "SOSS"
    #     return "You may only login between " + @SOSSstart.strftime("%b %d, %I:%M")  + " AM and " + @SOSSend.strftime("%b %d, %I:%M")   +" PM. "
    # when "SOSE"
    #   return "You may only login between " + @SOSEstart.strftime("%b %d, %I:%M")  + " AM and " + @SOSEend.strftime("%b %d, %I:%M")   +" PM. "
    # when "SOM"
    #   return "You may only login between " + @SOMstart.strftime("%b %d, %I:%M")  + " AM and " + @SOMend.strftime("%b %d, %I:%M") +" PM. "
    # end

    return "The yearbook preview is from February 13-15."
  end

  def can_login

    # @end = Time.new(2017,3,1,0)
return false
    # if Time.now >= @end
    #   return true
    # else
    #   return false
    # end
    # @SOHstart = Time.new(2016, 10, 2,23).in_time_zone('Hong Kong')
    # @SOHend = Time.new(2016, 10, 3, 15).in_time_zone('Hong Kong')

    # @SOSSstart = Time.new(2016, 10, 3, 23).in_time_zone('Hong Kong')
    # @SOSSend = Time.new(2016, 10, 4, 15).in_time_zone('Hong Kong')

    # @SOSEstart = Time.new(2016, 10, 4, 23).in_time_zone('Hong Kong')
    # @SOSEend = Time.new(2016, 10, 5, 15).in_time_zone('Hong Kong')

    # @SOMstart = Time.new(2016, 10, 5, 23).in_time_zone('Hong Kong')
    # @SOMend = Time.new(2016, 10, 6, 15).in_time_zone('Hong Kong')

    # @groupstart1 = Time.new(2016, 10, 6, 23).in_time_zone('Hong Kong')
    # @groupend1 = Time.new(2016, 10, 7, 15).in_time_zone('Hong Kong')

    # @groupstart2 = Time.new(2016, 10, 7, 23).in_time_zone('Hong Kong')
    # @groupend2 = Time.new(2016, 10, 8, 15).in_time_zone('Hong Kong')

    # @somspecialstart = Time.new(2016, 10, 8, 23).in_time_zone('Hong Kong')
    # @somspecialend = Time.new(2016, 10, 9, 15).in_time_zone('Hong Kong')

    # @specialstart = Time.new(2016, 10, 9, 16).in_time_zone('Hong Kong')
    # @specialend = Time.new(2016, 10, 13, 15).in_time_zone('Hong Kong')


    # case self.school
    # when "SOH" 
    #   if Time.current.in_time_zone('Hong Kong').between?(@SOHstart, @SOHend)
    #     return true
    #   else
    #     return false
    #   end
    # when "SOSS"
    #   if Time.current.in_time_zone('Hong Kong').between?(@SOSSstart, @SOSSend)
    #     return true
    #   else
    #     return false
    #   end
    # when "SOSE"
    #   if Time.current.in_time_zone('Hong Kong').between?(@SOSEstart, @SOSEend)
    #     return true
    #   else
    #     return false
    #   end
    # when "SOM"
    #   if Time.current.in_time_zone('Hong Kong').between?(@SOMstart, @SOMend)
    #     return true
    #   else
    #     return false
    #   end
    # end
   

    # case self.school
    # when "SOM"
    #   if Time.current.in_time_zone('Hong Kong').between?(@somspecialstart, @somspecialend)
    #     return true
    #   else
    #     return false
    #   end
    # else 
    #   return false
    # end

    # if Time.current.in_time_zone('Hong Kong').between?(@specialstart, @specialend)
    #   return true
    # else
    #   return false
    # end



  end


  def self.find_for_database_authentication(warden_conditions)
      conditions = warden_conditions.dup
      #raise conditions.inspect
      if login = conditions.delete(:id)
        where(conditions.to_hash).where(["student_id = :value", { :value => login }]).first
      else
        where(conditions.to_hash).first
      end
    end
  def create_or_update
      raise ReadOnlyRecord, "#{self.class} is marked as readonly" if readonly?
      account = Account.where(student_id: self.student_id).first
      if account
        self.id = account.id
      end
      result = new_record? ? _create_record : _update_record
      result != false
    end

    # create_or_update comes from persistence.rb

    def self.to_csv(options = {})
      (CSV.generate(options) do |csv|
        columns = %w(student_id name school yr course full_course double_major second_status minor cellphone_number email writeup feedback)
        csv << columns
        all.each do |account|
          csv << account.attributes.values_at(*columns)
        end
      end).encode('WINDOWS-1252', :undef => :replace, :replace => '')
    end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
	skip_before_action :verify_authenticity_token
	before_filter :check_for_cancel, :only => [:add_writeup, :edit_info]

	def index
		@school = current_account.school
		@events = Event.where(description: ["All", @school]).order(:start_time)
		@timeslot = Timeslot.find_by(id: current_account.timeslot_id)
		
		# @groupslot = Groupslot.find_by(student_id: current_account.student_id)
		
		if @groupslot.present?
			@groupshot = Groupshot.find_by(id: @groupslot.groupshot_id)
		end
	end	

	def group_signups
		@checkgroupslot = Groupslot.where(student_id: current_account.student_id)
		if @checkgroupslot.count > 0
			@has_groupshot = true
			@checkgroupslot = @checkgroupslot.first
			@timeslot = Groupshot.find(@checkgroupslot.groupshot_id)
		end
		@slots = Groupshot.all.order(:date).order(:start_time)
		@dates = ["2016-11-16", "2016-11-17", "2016-11-18", "2016-11-19", "2016-11-21", "2016-11-22", "2016-11-23"]
	end

	def sign_ups
		if current_account.timeslot_id.present? 
			@timeslot = Timeslot.find(current_account.timeslot_id)
		end

		@dates = ["2016-10-17", "2016-10-18", "2016-10-19", "2016-10-20","2016-10-21","2016-10-22","2016-10-24","2016-10-25","2016-10-26", "2016-10-27","2016-10-28","2016-10-29","2016-11-03","2016-11-04","2016-11-07","2016-11-08","2016-11-09","2016-11-10","2016-11-14","2016-11-15"]

		@slots = Timeslot.where(date: @dates).order(:start_time)
	end

	def search 
		idparams = params[:id]
		@student=Account.where(student_id: idparams).first

		if @student.timeslot_id.nil?
			@timeslot = "No timeslot."
		else
			@timeslot = Timeslot.find(@student.timeslot_id).to_s
		end

		respond_to do |format|
			format.html
			format.json {render json: @student, methods: :get_timeslot}
		end
	end

	def destroy 
		@account = Account.find(params[:id])
		@student = Student.find(@account.student_id)
		@student.update_attribute(:account, false)

	    @account.destroy

	    if @account.destroy
	        redirect_to accounts_admins_path, notice: "Account #{@account.student_id} deleted."
	    end
	end

	def reschedule
		@timeslot = Timeslot.find_by(id: current_account.timeslot_id)
		@timeslot.slots = @timeslot.slots + 1
		@timeslot.save

		current_account.timeslot_id = nil
		current_account.rescheduled = true
		current_account.save(validate: false)

		flash[:alert] = "Timeslot reset."
		redirect_to :back
	end

	def sign_up
	# 	@timeslot = Timeslot.find(params[:slot_id])

	# 	if @timeslot.slots > 0
			
	# 		@timeslot.slots = @timeslot.slots - 1
	# 		if @timeslot.slots < 0
	# 			flash[:alert] = "Slot already taken."
	# 			redirect_to sign_ups_accounts_path
	# 		else
	# 			@timeslot.save
	# 			current_account.timeslot_id = params[:slot_id]
	# 			current_account.save(validate: false)
	# 		end

	# 		redirect_to sign_ups_accounts_path
	# 	elsif @timeslot.slots == 0
	# 		flash[:alert] = "Slot already taken."
	# 		redirect_to sign_ups_accounts_path
	# 	end
		flash[:alert] = "You may not sign up."
		redirect_to :back
	end

	def group_signup
	# 	@timeslot = Timeslot.find(params[:slot_id])

	# 	if params[:group_name] != "" or params[:group_name].present?
	# 		if @timeslot.slots > 0 
	# 			@timeslot.slots = @timeslot.slots - 1
				
	# 			if @timeslot.slots < 0
	# 				flash[:alert] = "Slot already taken."
	# 				redirect_to group_signups_accounts_path
	# 			else
	# 				@timeslot.save
	# 				@groupslot = Groupslot.new
	# 				@groupslot.student_id = current_account.student_id
	# 				@groupslot.groupshot_id = params[:slot_id]
	# 				@groupslot.group_name = params[:group_name]
	# 				@groupslot.save
	# 				redirect_to group_signups_accounts_path
	# 			end
	# 		elsif @timeslot.slots == 0
	# 			flash[:alert] = "Slot already taken."
	# 			redirect_to group_signups_accounts_path
	# 		end
	# 	else
	# 		flash[:alert] = "Please enter a group name."
	# 		redirect_to group_signups_accounts_path
	# 	end
		flash[:alert] = "You may not sign up."
		redirect_to :back
	end

	def photoshoot
		@account = Account.where(student_id: params[:id]).first
		if @account.timeslot_id.present?
			@timeslot = Timeslot.find(@account.timeslot_id)
			@timeslot.slots = @timeslot.slots + 1
			@timeslot.save

			@account.timeslot_id = nil
			@account.save(validate: false)

			flash[:notice] = "Account #{@account.student_id} timeslot reset."
			redirect_to :back
		end
	end

	def slip
		@timeslot = Timeslot.find(current_account.timeslot_id)
		respond_to do |format|
	      format.html
	      format.pdf do
	        render pdf: "confirmation_slip",
	          layout: 'pdf.html.erb',
	          debug: true,
	          template: 'accounts/slip.pdf.erb',
	          show_as_html: params[:debug].present?,
	          margin:  {   top:               10,                     # default 10 (mm)
	                    bottom:            10,
	                    left:              10,
	                    right:             10 }
	      end
	    end
	end

	def groupslip
		@groupslot = Groupslot.where(student_id: current_account.student_id).first
		@timeslot = Groupshot.find(@groupslot.groupshot_id)


		respond_to do |format|
	      format.html
	      format.pdf do
	        render pdf: "group_confirmation_slip",
	          layout: 'pdf.html.erb',
	          debug: true,
	          template: 'accounts/groupslip.pdf.erb',
	          show_as_html: params[:debug].present?,
	          margin:  {   top:               10,                     # default 10 (mm)
	                    bottom:            10,
	                    left:              10,
	                    right:             10 }
	      end
	    end
	end

	def check_for_cancel
	  if params[:commit] == "Cancel"
	    redirect_to view_writeup_accounts_path
	  end
	end

	def timeslots
		@dates = []
		@dates_g = []
		Timeslot.where(type: nil).distinct(:date).order(:date).pluck(:date).each do |timeslot|
			instance_variable_set "@slots_#{timeslot.to_s.underscore}".to_sym, Timeslot.where(date: timeslot)
			@dates << "#{timeslot.to_s.underscore}"
		end

		Groupshot.distinct(:date).order(:date).pluck(:date).each do |timeslot|
			instance_variable_set "@slots_#{timeslot.to_s.underscore}".to_sym, Timeslot.where(date: timeslot)
			@dates_g << "#{timeslot.to_s.underscore}"
		end
	end

	def view_writeup
		@account = current_account
		#if !current_account.can_write
			#redirect_to accounts_path
		#end
	end

	def add_writeup
		@account = current_account

		if current_account.final_writeup
			redirect_to view_writeup_accounts_path
		elsif !current_account.can_write
			redirect_to accounts_path
		end
	end

	def admin_writeup
		@student = Account.find_by(student_id: params[:id])

		if @student.present? 
			if @student.writeup.present?
				flash[:notice] = "Student #{params[:id]} has a write-up."
				redirect_to :back
			else
				@student.update_attributes(writeup: params[:writeup])
				@student.update_attributes(final_writeup: true)
				flash[:notice] = "Student #{params[:id]} write-up added."
				redirect_to :back
			end
		else
			flash[:notice] = "Student #{params[:id]} not found."
			redirect_to :back
		end
	end

	def submit_writeup

	end

	def submit_final_writeup 
		current_account.update(final_writeup:  true)
		redirect_to edit_info_accounts_path
	end

	def edit_info
		@account = current_account
	end

	def reset_writeup 
		@student = Account.find_by(student_id: params[:id])

		if @student.present? 
			@student.update_attributes(final_writeup: false)
			flash[:notice] = "Student #{params[:id]} write-up set to temporary status."
			redirect_to :back
		else
			flash[:notice] = "Student #{params[:id]} not found."
			redirect_to :back
		end
	end

	def reset_feedback
		@student = Account.find_by(student_id: params[:id])

		if @student.present? 
			@student.update_attributes(feedback: nil)
			flash[:notice] = "Student #{params[:id]} feedback resetted."
			redirect_to :back
		else
			flash[:notice] = "Student #{params[:id]} not found."
			redirect_to :back
		end
	end

	def yearbook_preview
		@casualshot = current_account.yearbook_shot
		@togashots = CoursePage.select('page_number').where(course: current_account.course.upcase)
	end

	def addfeedback

		feedback = "["+params[:page_number]+"]"+"["+params[:name]+"]"+"["+params[:feedback]+"]"
		current_account.feedback = feedback
		current_account.save

		flash[:success] = "Feedback submitted!"
		redirect_to :back
	end

	def update		
		# if params[:writeup_submit]
		# 	@account = current_account
		# 	@account.update_attributes!(account_params)
		# 	redirect_to view_writeup_accounts_path
		# elsif params[:account_submit]
		# 	@account = current_account
		# 	@account.update_attributes!(account_params)
		# 	redirect_to accounts_path
		# else
			# redirect_to accounts_path
		# end

		current_account.update_attribute(:feedback, params[:feedback])
		flash[:success] = "Feedback submitted!"
		redirect_to yearbook_preview_path
	end

	def account_params
	  params.require(:account).permit(:writeup, :double_major, :minor, :cellphone_number, :full_course, :second_status, :email, :feedback)
	end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/group_signups.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'HOME', root_path, method: :get %></li>
        <li class=""><%= link_to 'ACCOUNT', accounts_path, method: :get %></li>
        <li class="dropdown active">
          <a href="#" class="dropdown-toggle active" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">SHOOT SLOTS &#x25BC;<span class="caret" style="border:transparent;margin-left:15px;"></span></a>
          <ul class="dropdown-menu shoot-dropdown">
            <li class=""><%= link_to 'PHOTOSHOOT SIGN UPS', sign_ups_accounts_path, method: :get %></li>
            <li class=""><%= link_to 'GROUPSHOOT SIGN UPS', group_signups_accounts_path, method: :get %></li>
          </ul>
        </li>
        <li class=""><%= link_to 'WRITE UPS', view_writeup_accounts_path, method: :get %></li>
        <li><%= link_to "LOG OUT", destroy_account_session_path, :method => :delete %></a>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class="container with-fixed-navbar">
  <h4 class="center-align" style="color:red"><%= flash[:alert] %></h4>
  
  <% if @has_groupshot %>
  
    <div class="confirmation-slip col-xs-10 col-xs-offset-1 col-sm-8 col-sm-offset-2">
      <div class="row">
        <h6 class="center-align">You are required to bring a print out of this confirmation slip to your photoshoot proper.</h6><br><br>
        <h3 class="center-align">AEGIS 2017</h3>
        <h3 class="center-align">YEARBOOK PHOTO SHOOT</h3>
        <h3 class="center-align">CONFIRMATION SLIP</h3>
      </div>
      <div class="row">
        <h4>This confirmation slip stands as proof that <span class="text-bold"><%= @checkgroupslot.group_name %></span>, represented by <span class="text-bold"><%= current_account.to_s %></span> agrees to all the terms and conditions that have been laid out by the AEGIS 2017 Editorial Board in the AEGIS 2017 Photoshoot Primer. We have fully read and understood the primer and am aware of the possible consequences we must face should we break any of the terms and conditions listed.</h4>
      </div>
      <div class="row">
        <h4>This slip also confirms that we have signed up on <span class="text-bold"><%=@timeslot.date.strftime("%A, %B %d, %Y")%> at <%= @timeslot.start_time.to_s + " - " + @timeslot.end_time.to_s%></span>.</h4>
        <%= button_to "SAVE AS PDF", groupslip_accounts_path(groupslot: @timeslot.id, format: 'pdf'), method: :get%>
      </div>
    </div>
  <% end %>
    <div class="row">
      <div class="row" id="account-sign-ups">
        <div class="col-xs-10 col-xs-offset-1 col-sm-6 col-sm-offset-3">
          <h3 class="center-align"><%=current_account.student_id %> - <%=current_account.name.downcase %></h3>
          <h4 class="center-align">Available timeslots are shown in case you want to reschedule.</h4>
          <!-- <ol>
            <h4><li>Click on the button of your preferred timeslot to sign up for that slot.</li></h4>
            <h4><li>Numbers show remaining number of slots. </li></h4>
            <h4><li>Please be sure of your slot; you will not be allowed to reschedule through the website.</li></h4>
          </ol> -->
        </div>

      </div>
      <div class="row table-responsive">
        <table class="table table-striped table-hover">
          <tr>
            <th class="right-align">Start time<br>End time</th>
            <th class="center-align">8:00 AM<br>9:00 AM</th>
            <th class="center-align">9:00 AM<br>10:00 AM</th>
            <th class="center-align">10:00 AM<br>11:00 AM</th>
            <th class="center-align">11:00 AM<br>12:00 PM</th>
            <th class="center-align">12:00 PM<br>1:00 PM</th>
            <th class="center-align">1:00 PM<br>2:00 PM</th>
            <th class="center-align">2:00 PM<br>3:00 PM</th>
            <th class="center-align">3:00 PM<br>4:00 PM</th>
            <th class="center-align">4:00 PM<br>5:00 PM</th>
            <th class="center-align">5:00 PM<br>6:00 PM</th>
          </tr>
          <% @dates.each do |date| %>
            <tr>
              <td class="right-align text-bold"><%= Date.parse(date).strftime("%a, %b %d") %></td>
              <% @sum = 0%>
              <% @slots.where(date: date).each do |slot| %>
                <% @sum = @sum + slot.slots %>
                <% if slot.slots >= 6 %>
                  <% @status = "success" %>
                <% elsif slot.slots < 6 && slot.slots > 0 %>
                  <% @status = "warning" %>
                <% elsif slot.slots == 0 %>
                  <% @status = "danger" %>
                <% end %>
                <%# if slot.slots == 0 %>
                  <td class="center-align">
                    <button type="button" class="btn btn-lg <%=@status%>" data-toggle="modal" data-target="#slot<%=slot.id%>" disabled>
                      <%= slot.slots %>
                    </button>
                  <%#button_to slot.slots, group_signup_accounts_path(slot.id), class: "btn #{@status}", disabled: true%></td>
                <%# else %>
                  <!-- <td class="center-align">
                    <button type="button" class="btn btn-lg <%#@status%>" data-toggle="modal" data-target="#slot<%#slot.id%>">
                      <%# slot.slots %>
                    </button>
                    <%#button_to slot.slots, group_signup_accounts_path(slot.id), class: "btn #{@status}"%></td> -->
                <%# end %>

                <!-- <div class="modal fade bs-example-modal-sm" id="slot<%=slot.id%>" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
                  <div class="modal-dialog modal-sm" role="document">
                    
                    <div class="modal-content">
                      <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h5 class="modal-title center-align" id="myModalLabel">Groupshoot Slot Signups</h5>
                      </div>
                      <div class="modal-body">
                        <h4 class="center-align">Slot details:</h4>
                        <h3 class="center-align"><%#Date.parse(date).strftime("%a, %b %d")%></span></h3>
                        <h3 class="center-align"><%# slot.start_time + " - " + slot.end_time %></h3><br>
                        <h4 class="center-align">Please indicate your group name:</h4>
                        <div class="row">
                          <div class="col-xs-12">
                            <form action="/accounts/group_signup" method="POST">
                              <input name="group_name" class="grpnm center-align" required>
                              <input name="slot_id" value="<%#slot.id%>" hidden><br>
                              <button type="submit" class="btn groupslot-confirm" disabled>Confirm Timeslot</button>
                            </form>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div> -->
              <% end %>
            </tr>
          <% end %>
        </table>
      </div>
    </div>
</div>

app/views/accounts/slot.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'HOME', root_path, method: :get %></li>
        <li class=""><%= link_to 'ACCOUNT', accounts_path, method: :get %></li>
        <li class="active"><%= link_to 'SIGN UPS', sign_ups_accounts_path, method: :get %></li>
        <li><%= link_to "LOG OUT", destroy_account_session_path, :method => :delete %></a>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>